development:
  adapter: postgresql
  encoding: utf8
  database: enchant_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: enchant_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: enchant_production
  pool: 5
  username:
  password:
